// Implements REQ-PIPE-006
//
// D1 helpers for the `scrape_runs` aggregation table. The coordinator
// opens a row (`startRun`), each chunk consumer accumulates its own
// token/cost/article counters (`addChunkStats`), and the final chunk
// flips the status to `ready` (`finishRun`). Stats feed the /history
// dashboard and the /stats tile widgets.
//
// Schema (live shape after migration 0010 — see migrations/README.md
// for the full migration index):
//
//   CREATE TABLE scrape_runs (
//     id                    TEXT PRIMARY KEY,    -- ULID from caller
//     model_id              TEXT NOT NULL,
//     started_at            INTEGER NOT NULL,    -- unix seconds
//     finished_at           INTEGER,             -- null while running
//     status                TEXT NOT NULL,       -- 'running'|'ready'|'failed'
//     chunk_count           INTEGER,             -- total chunks enqueued
//     tokens_in             INTEGER NOT NULL DEFAULT 0,
//     tokens_out            INTEGER NOT NULL DEFAULT 0,
//     estimated_cost_usd    REAL    NOT NULL DEFAULT 0,
//     articles_ingested     INTEGER NOT NULL DEFAULT 0,
//     articles_deduped      INTEGER NOT NULL DEFAULT 0,
//     -- migration 0008 — once-per-run gate so SCRAPE_FINALIZE is
//     -- enqueued exactly once even under chunk-consumer redelivery.
//     finalize_enqueued     INTEGER NOT NULL DEFAULT 0,
//     -- migration 0010 — once-per-run gate so the finalize merge is
//     -- recorded (article_sources rewritten, stats accumulated) at
//     -- most once per scrape, even under finalize-consumer redelivery.
//     finalize_recorded     INTEGER NOT NULL DEFAULT 0
//   );
//
// Time-source note: all helpers use `Math.floor(Date.now()/1000)` for
// second-precision unix timestamps. Callers that need deterministic
// tests can wrap `Date.now` via vitest's `vi.setSystemTime`.

// D1Database is ambient via @cloudflare/workers-types — no import needed.

/** Seed for `startRun`. `id` is a ULID generated by the caller so the
 * row's primary key is available synchronously before insert. */
export interface ScrapeRunSeed {
  id: string;
  model_id: string;
  /** Optional — the coordinator records the total chunk count once it's
   * computed the fan-out size. Defaults to NULL if unknown. */
  chunk_count?: number;
}

/** Per-chunk counters accumulated by `addChunkStats`. All fields are
 * additive — each call increments the row's running totals. */
export interface ChunkStats {
  tokens_in: number;
  tokens_out: number;
  estimated_cost_usd: number;
  /** Candidate articles this chunk tried to write. */
  articles_ingested: number;
  /** Candidates this chunk suppressed via canonical-URL or LLM dedupe. */
  articles_deduped: number;
}

/**
 * Insert a new `scrape_runs` row with `status='running'` and
 * `started_at=now`. Counter columns start at their DEFAULT 0 values.
 *
 * The caller already has the ULID (generated up-front so the
 * coordinator can stamp it into enqueued chunk messages), so we bind it
 * directly and let D1 enforce PK uniqueness.
 */
export async function startRun(db: D1Database, seed: ScrapeRunSeed): Promise<void> {
  const now = nowSeconds();
  // The schema has `chunk_count INTEGER NOT NULL DEFAULT 0`; binding
  // NULL explicitly bypasses the DEFAULT and trips the NOT NULL
  // constraint. Fall back to 0 so the coordinator can later UPDATE
  // the real chunk count once fan-out is known.
  const chunkCount = seed.chunk_count ?? 0;
  await db
    .prepare(
      `INSERT INTO scrape_runs (id, model_id, started_at, status, chunk_count)
       VALUES (?1, ?2, ?3, 'running', ?4)`,
    )
    .bind(seed.id, seed.model_id, now, chunkCount)
    .run();
}

/**
 * Accumulate one chunk's worth of stats into an existing run row. Every
 * counter column uses `col = col + ?` so two concurrent chunk consumers
 * won't clobber each other's updates — D1's serial writer makes this
 * safe by construction.
 */
export async function addChunkStats(
  db: D1Database,
  runId: string,
  stats: ChunkStats,
): Promise<void> {
  await db
    .prepare(
      `UPDATE scrape_runs
         SET tokens_in = tokens_in + ?2,
             tokens_out = tokens_out + ?3,
             estimated_cost_usd = estimated_cost_usd + ?4,
             articles_ingested = articles_ingested + ?5,
             articles_deduped = articles_deduped + ?6
       WHERE id = ?1`,
    )
    .bind(
      runId,
      stats.tokens_in,
      stats.tokens_out,
      stats.estimated_cost_usd,
      stats.articles_ingested,
      stats.articles_deduped,
    )
    .run();
}

/**
 * Close out a run by stamping `finished_at=now` and flipping `status`
 * to either `ready` (all chunks completed) or `failed` (a chunk hit its
 * retry ceiling or the coordinator aborted).
 *
 * The `WHERE status = 'running'` guard prevents a late-arriving failed
 * chunk (its retries exhausted after the run already reached 'ready'
 * via the COUNT(*) gate) from flapping the dashboard back to 'failed'.
 * Once a run leaves 'running' the status is final.
 */
export async function finishRun(
  db: D1Database,
  runId: string,
  status: 'ready' | 'failed',
): Promise<void> {
  const now = nowSeconds();
  // CF-002 follow-up: a redelivered last-chunk message can re-enter
  // finishRun. Stamping `finished_at = now` unconditionally would
  // shift the run's apparent duration forward on every retry. COALESCE
  // preserves the first-write timestamp so the history dashboard sees
  // when the run actually completed, not when the queue redelivered.
  await db
    .prepare(
      `UPDATE scrape_runs
         SET status = ?2,
             finished_at = COALESCE(finished_at, ?3)
       WHERE id = ?1 AND status = 'running'`,
    )
    .bind(runId, status, now)
    .run();
}

function nowSeconds(): number {
  return Math.floor(Date.now() / 1000);
}
