// Stub Worker entry point used only by the test pool's wrangler.test.toml.
// The real entry is generated by astro build into dist/_worker.js/index.js.
// Phase 5 will replace this with the cron dispatcher + queue consumer.
export default {
  async fetch(_request: Request, _env: Env): Promise<Response> {
    return new Response('news-digest', { status: 200 });
  }
};
